#!/bin/bash

#compiling
javac applet/Applet.java
javac -cp servlet/libs/servlet-api.jar servlet/Servlet.java
javac shared/*.java

#copying to tomcat
#applet
sudo cp -r applet/ /var/lib/tomcat7/webapps/simulation/
#servlet
sudo cp -r servlet/ /var/lib/tomcat7/webapps/simulation/WEB-INF/classes/
#shared
sudo cp -r shared/ /var/lib/tomcat7/webapps/simulation/WEB-INF/classes/
sudo cp -r shared/ /var/lib/tomcat7/webapps/simulation/
#website
sudo cp index.html /var/lib/tomcat7/webapps/simulation/
#resources
sudo cp -r shared/resources/ /var/lib/tomcat7/webapps/simulation/shared/

#start up tomcat (default is off)
sudo service tomcat7 start

#view website
chromium-browser localhost:8080/simulation/index.html

#shutdown tomcat (return to default)
sudo service tomcat7 stop
